input     : "/blue/bphl-florida/dongyibo/Dev_module_Enterovirus_assembly/fastqs"
output    : "/blue/bphl-florida/dongyibo/Dev_module_Enterovirus_assembly/output"

# Note: The parameter "input" and "output" are the absolute path. Do not include the "/" at the end of the paths.

